# Generated by Django 3.0.3 on 2020-02-07 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AddField(
            model_name='company',
            name='business_name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='company',
            name='doc_num',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='doc_type',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='founder_address',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='founder_email',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='founder_name',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='founder_phone',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='nit',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='site_url',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='total_emp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qualification',
            field=models.CharField(max_length=30),
        ),
    ]
