# Generated by Django 3.0 on 2019-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191203_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qualification',
            field=models.CharField(max_length=30),
        ),
    ]
