# Generated by Django 3.0 on 2019-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.CharField(choices=[('move', 'move'), ('travel', 'travel')], default='travel', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_situation',
            field=models.CharField(choices=[('working', 'working'), ('looking_for_job', 'looking_for_job')], default='working', max_length=20),
        ),
    ]
