# Generated by Django 3.0 on 2019-12-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191211_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='City1',
            new_name='city1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='City2',
            new_name='city2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='City3',
            new_name='city3',
        ),
    ]
