# Generated by Django 3.0 on 2019-12-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191213_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_salary',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
