# Generated by Django 3.0 on 2019-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191213_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
