# Generated by Django 3.0 on 2019-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191213_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='date_of_graduation',
            field=models.DateField(default=None),
        ),
    ]
