# Generated by Django 3.0 on 2020-02-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200217_1852'),
        ('user', '0008_education_date_of_graduation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
                ('is_evaluation', models.BooleanField(default=False)),
                ('is_interview', models.BooleanField(default=False)),
                ('is_offer', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Jobs')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Users')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Jobs')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Users')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='users',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='UserInterestedJobs',
        ),
    ]
