# Generated by Django 3.0 on 2020-02-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200217_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='profiles',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='profiles',
            new_name='user',
        ),
    ]
