# Generated by Django 3.0 on 2020-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200217_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='appointment_date',
            field=models.TextField(default=None, null=True),
        ),
    ]
