# Generated by Django 3.0.1 on 2020-04-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200217_1852'),
        ('user', '0017_auto_20200325_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Jobs'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
