# Generated by Django 2.2.11 on 2020-04-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200407_1021'),
    ]

    operations = [
        
    ]
